### ISSUE TITLE
Run requests in parallel?

### ISSUE THREAD

**Issue by Rusinas** [ferdikoomen/openapi-typescript-codegen#1323]
I noticed that if I perform multiple requests to the same endpoint simultaneously, they will run sequentially, but I need to run them in paralell in order to get all the data I need at the same time. Can't find this in documentation. I am using axios version.

**Comment by aktentasche** [comment]
I have the same issue, when I use Promise.all() to the same endpoint (for testing purposes) the requests are run sequentially. This is especially weird since the very "lowest" call returns a promise. I tried this with both the default "fetch" version as well as with axios (and axios.all()), same result.

**Comment by aktentasche** [comment]
Actually it was a problem in front of the screen.

I just did not understand how Promises work. You should pass Promises up to the highest layer and then await them there. If there are any awaits in between the whole concurrency collapses (I am using Vue 3 with Pinia).

**Comment by tannera** [comment]
This library doesn't handle the requests and their call order, you can control that when you invoke the generated functions. Just use a `Promise.all([request1(), request2()]).then(([resp1, resp]) => console.log('response received for both', resp1, resp2))`. 

Feel free to close this issue.
