### ISSUE TITLE
Custom Headers

### ISSUE THREAD

**Issue by aarshaw** [ferdikoomen/openapi-typescript-codegen#206]
Is it possible to add custom headers?

Currently looking to add an `Authorization` header: `Basic XXXXXXXXXX` - can only see a way documented for adding `Bearer` tokens ~ is there a way to add custom headers?

**Comment by ferdikoomen** [comment]
@aarshaw At the moment: No. Quick question:

1.  Do you want to add the headers through the API spec (not sure how, since support is limited i think)?
2. Do you want to support a per-request kind of header (where you can pass the header like a request parameter)?
3. Or do you want to set a generic header (a bit like the Bearer option)?

Cheers

**Comment by aarshaw** [comment]
No worries, we were able to use a different generator for this.

We needed to add a `Basic` authorization header.
