### ISSUE TITLE
OpenAPIV3 - Description not emitted for model properties defined via $ref

### ISSUE THREAD

**Issue by richgoldmd** [ferdikoomen/openapi-typescript-codegen#346]
Thank you for a great bit of work!

In the case where the property of a model is defined directly:

```json
"properties": {
                    "active": {
                        "description": "Active",
                        "type": "boolean"
                    },
}
```
The emitted code for the model includes the description as a comment:
```js
    /**
     * Active
     */
    active?: boolean;
```

However, when the property is defined via $ref, no comment is emitted:
```json
"properties": {
  "updated": {
                        "$ref": "#/components/schemas/dateTime"
                    },
```
where dateTime is defined:
```json
    "components": {
        "schemas": {
            "dateTime": {
                "description": "Accept RFC3339, RFC3339_EXTENDED or timestamp - Defaults to RFC3339_EXTENDED",
                "type": "string",
                "format": "date-time"
            },
   }
```

The emitted code is:
```ts
    updated?: dateTime;
```

I think I would expect the description from the references schema to appear in the output.

**Comment by ferdikoomen** [comment]
@richgoldmd this is by (OpenAPI) design. If you would download one of the 'official' generators: https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.20/swagger-codegen-cli-3.0.20.jar

And run the generator on these examples:
`java -jar ./swagger-codegen-cli-v2.jar generate -i mySpec.json -l typescript-aurelia -o example`

Then you will see the same result: that the description for the schema stays in the generated model and will not show where this schema is used. This makes sense, since the description of your schema explains what this schema is (for instance "Schema that holds a RFC3339 timestamp"). But the description of the property shows why / how the specific property is uses (for instance "Accept an RFC3339 timestamp, if empty will default to xyz").

**Comment by richgoldmd** [comment]
Thanks for the response, and for an excellent tool as well.
