### ISSUE TITLE
Generating wrong services

### ISSUE THREAD

**Issue by mikearnaldi** [ferdikoomen/openapi-typescript-codegen#620]
Generating a client for: ```https://raw.githubusercontent.com/CurrencyCloud/currencycloud-swagger/master/src/reference.yaml``` I get the endpoint for `operationId: FindAccounts` with a return type `Promise<any>` where the schema says `{ "accounts": Array<Account>, "pagination": Pagination }`

**Comment by ferdikoomen** [comment]
@mikearnaldi Ah yes i see it indeed, let me investigate what is going on here

**Comment by ferdikoomen** [comment]
@mikearnaldi technically the issue is this: In the response section for the `FindAccounts' operation it states this:

```
'200':
  description: Success.
  schema:
    properties:
      accounts:
        type: array
        items:
          $ref: '#/definitions/Account'
      pagination:
        $ref: '#/definitions/Pagination'
```

However, the `schema` should contain `type: object`. 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject
When that is present the response looks good:

```
Promise<{
   accounts?: Array<Account>,
   pagination?: Pagination,
} | string>
```
The string response is there due to the default response + the response header that is specified.

**Comment by ferdikoomen** [comment]
The /conversions/find path does this correctly for instance

**Comment by mikearnaldi** [comment]
Uh sorry for the issue definitely a bad schema, closing! Thanks for investigating
