### ISSUE TITLE
add support to abort request

### ISSUE THREAD

**Issue by Ti-webdev** [ferdikoomen/openapi-typescript-codegen#635]
I can't find a way to pass an abort signal.

Although all of client types supported the feature:
https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort
https://www.npmjs.com/package/node-fetch#request-cancellation-with-abortsignal

**Comment by ferdikoomen** [comment]
@Ti-webdev There is a branch for cancelable requests: https://github.com/ferdikoomen/openapi-typescript-codegen/tree/feature/cancelable This will be merged soon. In that branch you can do the following:
```
const promise = SomeService.someCall();
promise.cancel();
```
This works well if you are using Redux Saga's or even better: ReactQuery: https://react-query.tanstack.com/guides/query-cancellation. But since it will just have a `cancel()` method on the Promise, you can do whatever you want with it.

**Comment by Ti-webdev** [comment]
@ferdikoomen Wow. Im looking forward that.

**Comment by Dbuggerx** [comment]
Hi @ferdikoomen, would you know when that branch is going to be merged?

**Comment by dovca** [comment]
@ferdikoomen Any news about this? I feel it's an essential feature of any request related library. Thanks!

**Comment by ferdikoomen** [comment]
@Ti-webdev @Dbuggerx @dovca @knoefel Since version 0.11.0 we support cancelable requests in the form of cancelable promises (in order to support all possible client implementations and be compatible with a few popular middleware layers out there).

**Comment by wbern** [comment]
@ferdikoomen it seems that we run into issues with cancelable promises when using `async .. await` where typescript complains that a regular promise isn't returned.

There's also the case of mocking calls from the methods with jest, it seems it is now not possible to use the built in functions to mock promise returns.

Also it seems cancelable promises were shot down a few years ago by spec makers, so not entirely sure how much promise (no pun intended) we see in using cancelable promises for the future?

I'm curious if you've gotten this type of feedback before? Just genuinely worried and hope to gain more insight. Would not be against contributing with pull request to make adjustments if there are improvements we can make.

**Comment by alexanderdavide** [comment]
> @Ti-webdev There is a branch for cancelable requests: https://github.com/ferdikoomen/openapi-typescript-codegen/tree/feature/cancelable This will be merged soon. In that branch you can do the following:
> 
> ```
> const promise = SomeService.someCall();
> promise.cancel();
> ```
> 
> This works well if you are using Redux Saga's or even better: ReactQuery: https://react-query.tanstack.com/guides/query-cancellation. But since it will just have a `cancel()` method on the Promise, you can do whatever you want with it.

Can anyone give an example of how I would make cancelation of `CancalablePromise` work in React Query when calling `cancelQueries`?

**Comment by rjgotten** [comment]
> @ferdikoomen it seems that we run into issues with cancelable promises when using `async .. await` where typescript complains that a regular promise isn't returned.
> 
> There's also the case of mocking calls from the methods with jest, it seems it is now not possible to use the built in functions to mock promise returns.
> 
> Also it seems cancelable promises were shot down a few years ago by spec makers, so not entirely sure how much promise (no pun intended) we see in using cancelable promises for the future?

Exactly.

There's a reason cancelable promises were discontinued and that reason is they do not compose well.
They do not play nice with async/await and rather than passing a means of request cancellation down, you now have to trickle a cancellable promise _up_ at each stage.

Worse; you have to trickle up a custom promise that all adapters; wrappers; decorators; proxies; etc. have to be aware of and if they have additional async behavior they _must_ be able to construct a new instance of the same cancellable promise type to continue to propagate it up. Which is in practice intractable. (As the issue with Jest already illustrates nicely.)

CancelablePromise is an anti-pattern that needs to die. AbortController and AbortSignal are the way forward.
