### ISSUE TITLE
Media type with parameter generates to `any` type

### ISSUE THREAD

**Issue by sudall** [ferdikoomen/openapi-typescript-codegen#672]
We have a response definition in our spec that looks like this:
```
"200": {
  "description": "Standard response for successful HTTP requests.",
  "headers": {
  },
  "content": {
    "application/json; type=collection": {
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Distribution"
        }
      },
...
```
and the generated response type ends up being:
`Promise<any>`

If we change the media type from `application/json; type=collection` to `application/json`, the generated type looks correct:
`Promise<Array<Distribution>>`

Is there something invalid about `application/json; type=collection` as a value here in the spec, or is this simply a case that isn't supported by the generator yet?

**Comment by janhartigan** [comment]
I'm also seeing this issue. Our services use accept headers to define versions, so we can't go with the default json type. @ferdikoomen got any idea what might be going on?

**Comment by janhartigan** [comment]
So digging into this a bit more, basically the problem is in this function:

https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/openApi/v3/parser/getContent.ts

If it doesn't match a known content type, it will just return `null`, which defaults the response to `any`. There are a few ways to address this problem...

### Simple/naive solution

Modify this function to do something like:

```typescript
return Object.keys(content)[0] && content[Object.keys(content)[0]].schema;
```

This would make it more flexible to accept whatever value is used for the content key.

### Match accept request headers to content response using function overloads

I tried setting something up using generics, but using default values with generics seems to be a fundamentally intractable problem in TS. So instead a function overload approach is all that seems to be available:

```typescript
type ContentType = 'application/thing.v1+json' | 'application/thing.v2+json';

type GenericArg = {id: string, accept?: ContentType};
type ThingV1Arg = { id: string, accept?: 'application/thing.v1+json' };
type ThingV2Arg = { id: string, accept?: 'application/thing.v2+json' };

interface ThingV1 {
  foo: boolean;
}

interface ThingV2 {
  moo: string;
}

class ThingService {
  public static async getThing({id, accept}: ThingV1Arg): Promise<ThingV1>;
  public static async getThing({id, accept}: ThingV2Arg): Promise<ThingV2>;
  public static async getThing({id, accept = 'application/thing.v1+json'}: GenericArg): Promise<ThingV1 | ThingV2> {
    const result = await __request({
      method: 'GET',
      path: `/thing/${id}`,
      headers: { 'Accept': accept },
      errors: { 404: `Transaction not found` },
  });

  return result.body;
  }
}

const thingv1 = ThingService.getThing({id: 'whatever'});
const thingv2 = ThingService.getThing({id: 'whatever', accept: 'application/thing.v2+json'});
```

Obviously this requires synchronization between what values are available in the `Accept` request header and those that are enumerated in the `content` property for `Content-Type` response header values, but overall this produces the desired result. We could posssibly introduce a new configuration option, something like `validateAcceptHeadersInContentTypes` to throw an `Error` during generation when this doesn't work.

Having looked through the code, this seems to be a non-trivial undertaking, but it's definitely not impossible. I hope to have something working within the next month or so (as my work schedule permits), but before then I'd really like @ferdikoomen to offer his input if he can. I can take care of all the coding here, but without the blessing of the sole maintainer on this repo, my only other option would be to fork and republish under a different name (something I'd really like to avoid).

**Comment by ferdikoomen** [comment]
@janhartigan syncing accept header + response type sounds amazing, but indeed a lot of work :-) Maybe even parsing all unique responses (unique schemas) and creating a union would be the first step here. So that we at least get something like:

```
  public static async getThing({ id }: GenericArg): Promise<ThingV1 | ThingV2> {
    const result = await __request({
      method: 'GET',
      path: `/thing/${id}`,
      errors: { 404: `Thing not found` },
  });
```
Instead of only V1 or V2. That should not be that difficult. 

I will leave this thread open. In the mean time @sudall I will implement a very quick fix that would fallback to the first response type that defines a schema. That should resolve most common usecases.

**Comment by ferdikoomen** [comment]
@janhartigan @sudall I also pushed a few improvements for the 0.12.0 version. Although we can still improve this area a lot it should be much less stupid now :-) The new version should be published today or tomorrow
