### ISSUE TITLE
Use URLSearchParams for getQueryString

### ISSUE THREAD

**Issue by nikeee** [ferdikoomen/openapi-typescript-codegen#752]
There is a native API for building a query string:
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

This could replace parts of getQueryString:
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/1bd981d530cc7ffe5d091b1b3de397618429289f/src/templates/core/functions/getQueryString.hbs#L1-L19

Is this open for grabs?

**Comment by flaksp** [comment]
Seems like the purpose of `getQueryString` function is only for Internet Explorer support, because it does not support `URLSearchParams` according to MDN docs. `URLSearchParams` also does not handle objects inside query strings, but there is PR #713 that solves this issue we are awaiting to be merged.

**Comment by ferdikoomen** [comment]
@nikeee Indeed that was the main reason to support some older browser, but i think we can start dropping support for Internet Explorer and start supporting Edge on the way forward (since Microsoft announced the end-of-life date for our favourite browser) https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/
