### ISSUE TITLE
Generated code does not compile with Typescript 4.4 and the exactOptionalPropertyTypes flag set to true

### ISSUE THREAD

**Issue by matthelliwell2** [ferdikoomen/openapi-typescript-codegen#823]
The generated OpenAPI.ts file looks like:
`type Config = {
    BASE: string;
    VERSION: string;
    WITH_CREDENTIALS: boolean;
    TOKEN?: string | Resolver<string>;
    USERNAME?: string | Resolver<string>;
    PASSWORD?: string | Resolver<string>;
    HEADERS?: Headers | Resolver<Headers>;
}

export const OpenAPI: Config = {
    BASE: 'https://your-domain.atlassian.net',
    VERSION: '1001.0.0-SNAPSHOT',
    WITH_CREDENTIALS: false,
    TOKEN: undefined,
    USERNAME: undefined,
    PASSWORD: undefined,
    HEADERS: undefined,
};`

TOKEN, USERNAME, PASSWORD and HEADERS are defined as optional with type string | Resolver<string>. Therefore with the exactOptionalPropertyType flag they cannot be set to undefined.

**Comment by ferdikoomen** [comment]
@matthelliwell2 More will fail when you specify exactOptionalPropertyTypes, for instance for OpenAPI model's it's quite normal to have non defined properties in modes. Examples like:
```
export type User = {
    readonly id: string;
    firstname: string;
    surname: string;
    nickname?: string;
    age?: number;
}
```
Where age and nickname might be properties the database / API does not know. We cannot make a model like:
```
export type User = {
    readonly id: string;
    firstname: string;
    lastname: string;
    nickname?: "user 1 | someothernickname | whoot | 1337";
    age?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 ..... 98 | 100;
}
```
Since not all combinations are (off course) known upfront.
