### ISSUE TITLE
Base path and Endpoint path accumulates double slash ('/')

### ISSUE THREAD

**Issue by altarrok** [ferdikoomen/openapi-typescript-codegen#890]
We are using: Spring REST backend, generating using springfox-swagger, on the frontend, we are using React and this library to generate api client services. 

Conditions to reproduce:
* Generated client config should have: ```BASE: 'http://localhost:8080/',```
* Generated client controller service should have a method with path starting with '/': ```/foo/${boo}/hoo```

500 error in backend: 
```The request was rejected because the URL contained a potentially malicious String "//"```
Frontend request link: 
```http://localhost:8080//foo/57a32e87-7638-4ad0-b566-fcb7b6210348/hoo/```

The Swagger docs (OpenAPI spec) doesn't have double slashes, so I believe this library should handle this double slash case.

Please let me know if additional information is needed, or any debugging work needed, thank you!!

**Comment by ferdikoomen** [comment]
@altarrok The paths MUST start with a slash according to the spec, but the `server` (V3) or `basePath` (V2) have no hard requirements to not end on a "/" character... however it makes sense, since the urls are concatenated. I have pushed a fix to the development branch. I want to fix a few smaller issue and will release a new version next week.
