### ISSUE TITLE
Use OpenAPI `title` field for generating service client name

### ISSUE THREAD

**Issue by jabalsad** [ferdikoomen/openapi-typescript-codegen#932]
Hello,

Currently, when generating a service client from the OpenAPI spec, we end up with classes named `ServiceService`. The current CLI supports a `--postfix` option that allows you to call it something slightly different, e.g. `ServiceFoo`. However this is not ideal for two reasons:

1. If we wanted the class to be called `FooService` it is not possible with the postfix option.
2. The service name is duplicated in the package.json file since you need to specify `--postfix Foo`, but this information is already contained in the OpenAPI spec.

To maintain backwards compatibility, perhaps a `--useTitle` flag can be introduced that reads the contents of this openapi field and uses it to name the client classes and exports.

**Comment by ferdikoomen** [comment]
@jabalsad There has been a small change in the development branch. Services without a `tags` are now not named and will be exported as `Service` and not as `ServiceService`, you can change this with the `postfix` param too `Api`. However if you want to generate correct names for your services you need to make sure the `tags` property in the OpenAPI spec is filled in:
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#operationObject (see first prop)
We cannot rely on some package.json file, since the generator should just rely on the Spec for any information.
