### ISSUE TITLE
Support nominal typing of identifiers

### ISSUE THREAD

**Issue by zbyte64** [ferdikoomen/openapi-typescript-codegen#998]
**Describe the solution you'd like**

I would like nominal typing to be applied to id fields to prevent UI developers from mixing or interchanging ids across resource types.
The following discusses how to achieve nominal typing in typescript: https://github.com/Microsoft/Typescript/issues/202

I imagine there isn't enough metadata in OpenAPI to accomplish this, but figured I'd give voice to this compelling use case.

**Comment by ferdikoomen** [comment]
@zbyte64 Do you have a OpenAPI spec with details on this? There is a feature in OpenAPI that currently this generator does not support, it's called discriminator mapping (https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#discriminator-object). Is that what you mean?

**Comment by sam-mfb** [comment]
Just came across this issue as we have the same question.  I don't think the original question was actually answered by discriminators in OpenApi.  As I understand it that allows for a form of polymorphism similar to what typescript offers via discriminated unions.

As I understand the original question it is about whether there is a way to generate "nominal types" from OpenAPI types, that is to generate a typescript type like the following:
```typescript
type MyObject = {
  id: Id
  someString: string
  someNumber: number
}
```
where the id field is actually just a number in the JSON, but gets converted to a branded type in Typescript so that the id field is not type compatible with a number type.  Such nominal types are doable in typescript by, for example, creating a type like:
```typescript
type Id = number & {
   // only exists in the typing to ensure type incompatibility with "normal" numbers
  _brand: string
}
var x = 3 as Id
x = 4 //errors
```
You can see a more detailed example [here](https://www.typescriptlang.org/play?#code/PTAEEFQOwewWwJZQIYBtQBcCeAHApqAM5aEZ5yhx7JSGYAWyGo1AxvZrgQnQK5QIAjrzwBYAFAhQNACYsAbniigEAM0746jRQwKFkVUDKbJQWGL1CsasZskKEEAcygSpyVgCcYDjXkIAdBJuYAAqXADKXgg4GADkdNj4RCRkFDxEGJ68rBi8nmgANKAA7vQI7JTUtCEq6hj0BEncdISM+HKoCADWBKYyOd3FCPF0-YMBoACS6si1TjA+BIxjqOgNegZ9GFkIAEa8ZGNjRoPFG8oj0qiEMLUZ46zdkwCaFlY0oKjUnspwMJ5lnhAQAuFgADwMOG+INI2Vy+TQAFokkgnMFJGFynRrMptAQZAUSnsPN1CMVVACIVDvrpAdJ6dZCP5amVgX1Mp40aAqVBeHA9sCPnjkDpCPhWAg0FYYFAyOC7FA5OZeLUZLK4swSjRmBgYAohXBkL1dKB5GgRIkCrRVMCCntvpMAGIA2p4SFwaF4EEhWpI0CgACqzM80ygOEOoAiuygTjoAAp+PpbQBKP0B0LWwioJgIWVRmNx9NBkPTGRKDBqCq5-MAOX5gs8hGL4FYrH8dFCMF6NXEtQA6gRcaAnHhmP9SDz6o0zRaCKpvBRTLBECh1lxasRSORSiMOKYujtaXsrjB1O6sqZWDBy0E+5jQIO4vSFty9aBeMzpJc5cDmbk8zXPxihKPdpA-ARhDEB9r1oS8kGYJBTUpTwKDPcCcG8fBPGwD41jwOQAH1CL2a05HjBoeHuHFZUUOVAJTUpykqI1ejoK4EE9HxHAdJp9XsRwXGkWpYFQ6U4TffjQAANTQBBjDIGQpnDQ5oy5WM7wkZoZLkhSCOUiMMDU7kAF5OW5AAyUAAG9QGI0jZDBAAiYMhQMyMAAUfGYWSugUwCnNAABfABuDEpEHXc1g-L9TFUfgAPzd9LxtAEl3M2NMDuB9TF8+SmH0lSjMLUB-QOXUZxwGAENKAEGmgGBK1jaiGCYUo8GfAgACtP2YQiyDWNFCNAcJ8CiLlYlaxDRkwbI8E08RYMnc0-IK1zPHc5gzPjJBDLBCTY0YkyAD4bIkAMluYRxPW+PK9KUorQDM3bDgCQFoQ8PB42AAAdAAeYAnGKJzABMiJyUzC8QA0BPJfiITivTugqHsM6Q6CRxTNuM2NIdC8KwFrGASna4UrEBArQHiqBEtoJiKg4UDotlVAsGkNs8FiWoLFDKA8GJlckGlZpilkBqKoIUdeYKdADqcPwFsu0BMIQ2stie0B4xQKgwQxwrDOxpwjtO6zzplWgYEdVAYCcTWtghiQ8fvKQXVDd0aTwYpGkBBIiHgAgk2QW0VEehd4HAz9gWKV9mofBpvF4JwOA2WdVr1UNRYuUBBW5NArZKAisqzghld-GQfXvRWXq20AnLQYEMHjOI9hgPY9lZjBkF4wg4hTJzIcVlb8sxx6zMHvT1s2naivt8QS4wVWqHjMfkc2mfagAeWUZPGq90BGCVYocAEt8Z34JFl8UjK5b1Wo54XghGfQAoeA5a9PQQb5Xc8bxPHLiQ762FPQya8HxvEsMOcmcgrzwEwngRotAEA6BgIoTw8gEB8ynLoNUahbSAjlKUZAJBC5eGoGQBqq4hZcHJN+OQGwECeFqJecsSIzyqHYlvbEoAAAsAAGHhMo4BUHwVbTKABxEYAAJXgewVAOBEOXEAtR6A7BwIQEEIAnB7mkQEN+wAACyFRvC3FUBgYAo08DjRiKYnghBLTAAAEw8Psb6HKSoGAZCqpOB4I5yZXX5EaTwWAFHACUSotRIBEDsDQAALzrk8BAOj4DAAFmuFEuA0RIiQGkzQ0RYghPEEAA)

So, I read the original question as if this codegen could support that.  I agree it would be useful (we use nominal types extensively in our code to ensure developers don't do things like add together identifiers or concatenate urls), but I think the logically prior question is whether there is anyway to encode this type of typing in to an OpenApi json.  There is nothing obvious to me in the spec that could be used for that purpose.  In other words, I don't see any field/property that could be used in a schema to tell the codegen utility: "treat this number/string type different than other number/string types"

If anyone has thoughts on how to do that, presumably we could then see if nominal types could be added to this utility.

**Comment by dani-z** [comment]
@ferdikoomen thanks for pointing this out. I will comment on this just for context, are there any plans to support this? 
I evaluated this library on the basis of supporting OpenAPI 2.0 and 3.0 as per the README but now I am stuck as this particular feature is actually not supported. 
In any case, I think updating the README file would be helpful.

Cheers
